### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by VL-IT-Service** [f7a8/mosaik2#3]
jens@Office001 ~/Projekte/mosaik2 (main)$ make test
mkdir -p test/flower
wget -N "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz" --directory-prefix=/tmp
--2023-05-16 18:07:04--  https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz
Auflösen des Hostnamens storage.googleapis.com (storage.googleapis.com) … 2a00:1450:4001:810::2010, 2a00:1450:4001:80e::2010, 2a00:1450:4001:80f::2010, ...
Verbindungsaufbau zu storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:810::2010|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 228813984 (218M) [application/x-compressed-tar]
Wird in ‘/tmp/flower_photos.tgz’ gespeichert.

flower_photos.tgz   100%[===================>] 218,21M  11,4MB/s    in 20s     

2023-05-16 18:07:25 (10,8 MB/s) - ‘/tmp/flower_photos.tgz’ gespeichert [228813984/228813984]

wget -N "https://upload.wikimedia.org/wikipedia/commons/5/52/2014.03.29.-08-Mannheim_Neckarau_Waldpark-Wiesen-Schaumkraut.jpg" --directory-prefix=/tmp
--2023-05-16 18:07:25--  https://upload.wikimedia.org/wikipedia/commons/5/52/2014.03.29.-08-Mannheim_Neckarau_Waldpark-Wiesen-Schaumkraut.jpg
Auflösen des Hostnamens upload.wikimedia.org (upload.wikimedia.org) … 2620:0:862:ed1a::2:b, 91.198.174.208
Verbindungsaufbau zu upload.wikimedia.org (upload.wikimedia.org)|2620:0:862:ed1a::2:b|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 5868357 (5,6M) [image/jpeg]
Wird in ‘/tmp/2014.03.29.-08-Mannheim_Neckarau_Waldpark-Wiesen-Schaumkraut.jpg’ gespeichert.

2014.03.29.-08-Mann 100%[===================>]   5,60M  10,9MB/s    in 0,5s    

2023-05-16 18:07:26 (10,9 MB/s) - ‘/tmp/2014.03.29.-08-Mannheim_Neckarau_Waldpark-Wiesen-Schaumkraut.jpg’ gespeichert [5868357/5868357]

tar xfz /tmp/flower_photos.tgz -C test/flower
find test/flower/flower_photos -type f -iregex '.*\.jpe?g$' -size +10000c -size -100000000c -fprintf test/flower/flower_photos.file_list "%p\t%s\t%T@\n" 
bin/mosaik2 init -r 8 test/flower/flowerphotos8
mosaik2 database directory (test/flower/flowerphotos8) created
bin/mosaik2 init -r 16 test/flower/flowerphotos16
mosaik2 database directory (test/flower/flowerphotos16) created
bin/mosaik2 index -q test/flower/flowerphotos8 < test/flower/flower_photos.file_list
job #0, jobs:1 img/min:-nan load:6.05
job #1000, jobs:1 img/min:2500.00 load:6.86
job #2000, jobs:5 img/min:2727.27 load:6.57
job #3000, jobs:1 img/min:2903.23 load:7.05
bin/mosaik2 index -q test/flower/flowerphotos16 < test/flower/flower_photos.file_list
job #0, jobs:1 img/min:-nan load:6.27
job #1000, jobs:1 img/min:3750.00 load:6.63
job #2000, jobs:1 img/min:3529.41 load:6.84
job #3000, jobs:6 img/min:3913.04 load:6.50
bin/mosaik2 duplicates test/flower/flowerphotos8
test/flower/flower_photos/sunflowers/4933230161_12f3ee7587.jpg
test/flower/flower_photos/tulips/8695372372_302135aeb2.jpg
test/flower/flower_photos/sunflowers/5293283002_9b17f085f7_m.jpg
bin/mosaik2 duplicates test/flower/flowerphotos16
mosaik2: src/libmosaik2.c:784: check_thumbs_db: Assertion `get_file_size(md->tileoffsets_filename) == element_count * md->tileoffsets_sizeof' failed.
make: *** [Makefile:59: test] Abgebrochen (Speicherauszug erstellt)
jens@Office001 ~/Projekte/mosaik2 (main)$

**Comment by f7a8** [comment]
Could you share the ouput of
bin/mosaik2 info test/flower/flowerphotos8
bin/mosaik2 info test/flower/flowerphotos16
if it works?

**Comment by VL-IT-Service** [comment]
jens@Office001 ~/Projekte/mosaik2 (main)$ bin/mosaik2 info test/flower/flowerphotos8
path=test/flower/flowerphotos8
id=1450de2bddd83
db-format-version=6
database-image-resolution=8
db-size=2462319
created-at=Tue May 16 23:01:02 2023
last-indexed=Tue May 16 23:02:38 2023
last-modified=Tue May 16 23:03:38 2023
element-count=3664
duplicates-count=3
invalid-count=0
valid-count=3661
tileoffsets-count=0
histogram-color=120.050140 108.961609 77.671921
histogram-stddev=70.679787 66.248955 62.589622
jens@Office001 ~/Projekte/mosaik2 (main)$ bin/mosaik2 info test/flower/flowerphotos16
path=test/flower/flowerphotos16
id=b0285858de045
db-format-version=6
database-image-resolution=16
db-size=8423959
created-at=Tue May 16 23:01:02 2023
last-indexed=Tue May 16 23:03:38 2023
last-modified=-
element-count=3664
duplicates-count=0
invalid-count=0
valid-count=3664
tileoffsets-count=0
histogram-color=119.804047 108.821053 77.627190
histogram-stddev=53.462837 51.028339 47.337223
jens@Office001 ~/Projekte/mosaik2 (main)$

**Comment by f7a8** [comment]
Strange. The database of the second snipped was created after the first post, but I guess the assert function fails always in your case. The test case did run on several distros, but never watched that. 
Maybe the file locking does not lock properly during the index mode.  Could you provide the dir listings?
ls -la test/flower/flowerphotos8
ls -la test/flower/flowerphotos16

**Comment by VL-IT-Service** [comment]
works with the newest version.
THX
