### ISSUE TITLE
join fails to create link

### ISSUE THREAD

**Issue by VL-IT-Service** [f7a8/mosaik2#4]
enrich data from results file my_db
data enriched (filenames and hashes)
0/672 create symlink my_db:16439 /home/jens/Bilder/2015/IMG_9456.JPG
error creating symlink /home/jens/.mosaik2/mosaik2.860dae62fe352f6be02ea77ee93b458a for /home/jens/test1//home/jens/Bilder/2015/IMG_9456.JPG
error message =>: File exists

/home/jens/test1  : working directory
/home/jens/Bilder/2015/IMG_9456.JPG  : path of pictures
seems the tool merges current working directory and the path to the files

**Comment by f7a8** [comment]
The simple test case does use relative file paths, but if you use the readme example absolute filenames are used in the database.  93a5cea2df87a787f2124f327410c7887bca235b should have fixed this and work now with absolute file paths.
